export const TOGGLE_TODO = 'TOGGLE_TODO';
export const ADD_TODO = 'ADD_TODO';

export const ADD_TODO_BATCH = 'ADD_TODO_BATCH';
export const ADD_TODO_BATCH_PENDING = 'ADD_TODO_BATCH_PENDING';
export const ADD_TODO_BATCH_FULFILLED = 'ADD_TODO_BATCH_FULFILLED';
export const ADD_TODO_BATCH_REJECTED = 'ADD_TODO_BATCH_REJECTED';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_ACTIVE = 'SHOW_ACTIVE';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
